### PR TITLE
Fix serverconfig path

### PR DESCRIPTION
**Pull request by riboyama**
Change _config.txt_ to _serverconfig.txt_

### CODE REVIEW

**Comment by riboyama** [comment]
@JACOBSMILE Could you merge this anytime soon?

**Comment by JACOBSMILE** [comment]
Hi @riboyama 

I'll need to update the README to reflect, the better change would be to update the first check to reflect the readme, making it "config.txt" across the board and not "serverconfig.txt".

Anyways, I will be able to review and resolve it this evening after work. Thanks! 👍

**Comment by riboyama** [comment]
Ah nice! I had some trouble mounting the confix.txt since this check is in entrypoint:
https://github.com/JACOBSMILE/tmodloader1.4/blob/1775cbf1e72f36103d1c271416d6f0bf5647dc0a/entrypoint.sh#L6

However the startup command uses:
https://github.com/JACOBSMILE/tmodloader1.4/blob/1775cbf1e72f36103d1c271416d6f0bf5647dc0a/entrypoint.sh#L92

I think it may be better to rename everything to **server**config.txt, as that is also what terraria uses by [default](https://terraria.fandom.com/wiki/Server)

**Comment by JACOBSMILE** [comment]
I fixed this in the most recent commit to the master branch, so I am going to close this PR.

**Pull request closed without merging**
